### PR TITLE
Update wbsite

### PR DESCRIPTION
**Pull request by michaldengusiak**

### CODE REVIEW

**Review by michalinadengusiak — CHANGES_REQUESTED** [review]
Instead of `Here I am` it would be splendid if you changed it into `Here am I`. Maybe more graphics and a little more colour?

**Comment by mdengusiak** [comment]
@michalinadengusiak  please check that you are in the correct branch

**Comment by michalinadengusiak** [comment]
@mdengusiak 
Okay noticed, please check my other request!

**Comment by mdengusiak** [comment]
OK great will be added soon during next session

**Comment by michalinadengusiak** [comment]
I will wait till that time!:stuck_out_tongue_winking_eye:

**Comment by mdengusiak** [comment]
@michalinadengusiak ok done :)

**Review by michalinadengusiak — APPROVED** [review]
Very nicely done! Thank you for listening to me now the website has more life!

**Pull request merged**
